#!/bin/sh

set -e

cd "$(dirname "$0")"

echo '##################################################################################'
echo "# THIS FILE IS AUTO GENERATED BY RUN \`sh metamake.sh\`. DO NOT MODIFY IT MANUALLY #"
echo '##################################################################################'
echo ''
echo 'FLAG_IF_TARGETS_INCLUDED = true ||'


VARIANTS=".0 .1 .2 .0.debug .1.debug .2.debug .0.debug.address .1.debug.address .2.debug.address"

emit_exe_target() {
  for VARIANT in $VARIANTS; do
    printf '\tout/exe/%s%s.exe \\\n' "$1" "$VARIANT"
  done
}

emit_lib_target() {
  for VARIANT in $VARIANTS; do
    NAME="libminirt_$1$VARIANT.$2"
    if [ "$1" = '' ]; then
      NAME="libminirt$VARIANT.$2"
    fi

    printf '\tout/%s/%s \\\n' "$2" "$NAME"
  done
}


printf 'EVERYTHING = \\\n'

while IFS="=" read -r exe_name _unused;
do
  emit_exe_target "$exe_name"
done < ../data/exe.properties

while IFS="=" read -r lib_name _unused;
do
  emit_lib_target "$lib_name" so
done < ../data/so.properties

while IFS="=" read -r lib_name _unused;
do
  emit_lib_target "$lib_name" a
done < ../data/a.properties

printf '\n'
