#!/bin/sh

set -e

cd "$(dirname "$0")"

echo '##################################################################################'
echo '# THIS FILE IS AUTO GENERATED BY RUN `sh metamake.sh`. DO NOT MODIFY IT MANUALLY #'
echo '##################################################################################'
echo ''

printf 'TARGET = \\\n'
printf '\tout/exe/minirt.0.exe \\\n'
printf '\tout/exe/minirt.1.exe \\\n'
printf '\tout/exe/minirt.2.exe \\\n'
printf '\n'


VARIANTS=".0 .1 .2 .0.debug .1.debug .2.debug .0.debug.address .1.debug.address .2.debug.address"

emit_exe_target() {
  for VARIANT in $VARIANTS; do
    printf '\tout/exe/%s%s.exe \\\n' "$1" "$VARIANT"
  done
}

emit_lib_target() {
  for VARIANT in $VARIANTS; do
    NAME="libminirt_$1$VARIANT.$2"
    if [ "$1" = '' ]; then
      NAME="libminirt$VARIANT.$2"
    fi

    printf '\tout/%s/%s \\\n' "$2" "$NAME"
  done
}


printf 'EVERYTHING = \\\n'

cat ../data/exe.properties | while IFS="=" read -r exe_name _unused;
do
  emit_exe_target "$exe_name"
done

cat ../data/so.properties | while IFS="=" read -r lib_name _unused;
do
  emit_lib_target "$lib_name" so
done

cat ../data/a.properties | while IFS="=" read -r lib_name _unused;
do
  emit_lib_target "$lib_name" a
done

printf '\n'
